### ISSUE TITLE
Ready to go live!

### ISSUE THREAD

**Issue by 3mmaRand** [posit-conf-2023/programming-r#10]
Hello @mine-cetinkaya-rundel ,
When you have a moment, please could you make this repo public - assuming that's ok with the posit team.
Thanks,
Emma and Ian

**Comment by mine-cetinkaya-rundel** [comment]
Done!

Would you like GitHub pages turned on as well?

**Comment by 3mmaRand** [comment]
oh yes! Thanks so much for remembering. That was the main point!

**Comment by mine-cetinkaya-rundel** [comment]
Alright, and made you admin in case you want to change GitHub pages settings
