### ISSUE TITLE
project to work in

### ISSUE THREAD

**Issue by ijlyttle** [posit-conf-2023/programming-r#39]
Hi @3mmaRand,

Instead of creating a project from scratch,

https://github.com/posit-conf-2023/programming-r/blob/cf8fb0d260f8e0de0caab07475a54cf382f65b1b/01-functions-01.qmd#L169-L173

would you consider something like this?

`````
```{r}
#| eval: false

usethis::use_course("posit-conf-2023/programming-r-exercises")
```
`````

**Comment by 3mmaRand** [comment]
@ijlyttle yes, most definitely. I'll make that change
